### PR TITLE
Implemented pre-release feature

### PR DESCRIPTION
**Pull request by christian-kreuzberger-dtx**
Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>

This implements #15.

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
There is a problem with the composer-install for this PR, though I did not change anything regarding the composer file.

```
Your lock file does not contain a compatible set of packages. Please run composer update.
Error: Your lock file does not contain a compatible set of packages. Please run composer update.
```

**Comment by WyriHaximus** [comment]
@christian-kreuzberger-dtx Just fixed the composer issues, can you rebase the PR on the default branch?

**Comment by christian-kreuzberger-dtx** [comment]
Will do it later today!

**Comment by christian-kreuzberger-dtx** [comment]
Sorry for the delay. Rebased it now, unit tests are still failing, but composer seems to work. I'll look into the tests later.

**Comment by christian-kreuzberger-dtx** [comment]
I had some challenges with the CI workflows and tests:

1. I found out that I can not change the order of outputs, therefore I had to restructure my code changes.
2. The fallback in case of non_strict checks was problematic, I had to change it to support `-` and split the string before appending a `.0` to it
3. Code style checks: In my opinion the codestyle checks are way too strict for an open source project. This will drive contributors away (or they will just abandon PRs).
4. Mutant/Infeciton: I have no idea what this does or what I have done wrong, please advise.

**Comment by WyriHaximus** [comment]
> I had some challenges with the CI workflows and tests:
> 
> 1. I found out that I can not change the order of outputs, therefore I had to restructure my code changes.

There isn't, never knew that?

> 2. The fallback in case of non_strict checks was problematic, I had to change it to support `-` and split the string before appending a `.0` to it

Looks like it works now right?

> 3. Code style checks: In my opinion the codestyle checks are way too strict for an open source project. This will drive contributors away (or they will just abandon PRs).

This has been on my mind in a more vague sense lately. Got the feeling it is adding more drag then it should for my as well. I'll adjust that soon and drop a bunch of the strict rulings. Any specific ones that got in your way?

An alternative consideration could be to not make them mandatory, or not run them for external PR's and fix it after the contribution.

> 4. Mutant/Infeciton: I have no idea what this does or what I have done wrong, please advise.

It's a mutation testing tool that tests the code for its susceptibility for the introduction of bugs. Probably refs point 3 as well. We can ignore it for now and I'll have a look at it after this PR has been merged

**Comment by christian-kreuzberger-dtx** [comment]
>> I found out that I can not change the order of outputs, therefore I had to restructure my code changes.
>
> There isn't, never knew that?

If I change the order of the
```
::set-output name=major
::set-output name=minor
::set-output name=patch

::set-output name=v_major
::set-output name=v_minor
::set-output name=v_patch
```
to (e.g.)

```
::set-output name=major
::set-output name=minor

::set-output name=v_major
::set-output name=v_minor

::set-output name=patch
::set-output name=v_patch
```

the tests failed (with a message indicating that the wrong strings were compared). Just an observation, not a critic ;)

ad 2: yes it does, it's just not pretty

ad 3: In my opinion things like equal signs that need to be aligned with surroundings and "unnecessary newlines" should be skipped. I understand the need of it, and you can always auto-apply them once in a while, but they should not be forced.

ad 4: thanks

**Comment by WyriHaximus** [comment]
@christian-kreuzberger-dtx Thanks! Will address those issues and tag a release tonight :+1: .

**Comment by WyriHaximus** [comment]
@christian-kreuzberger-dtx FYI I've opened #22 to make the build green again by making some small changes to make infection happy, and address the issue of the output had to be in order.

**Pull request merged**
