### PR TITLE
add min_version input

### PR DESCRIPTION
**Pull request by csmith23**

### CODE REVIEW

**Comment by WyriHaximus** [comment]
@csmith23 Why did you submit and then close this? I'm not immediately opposed to adding this, but I feel I'm missing something?

**Comment by csmith23** [comment]
@WyriHaximus sorry, I meant to open it into my fork but accidentally opened it into this one

**Comment by WyriHaximus** [comment]
@csmith23 Purely out of interest, but have you considered PRing whichever improvements you made in your fork back into this action?

**Comment by csmith23** [comment]
@WyriHaximus yeah I'd be happy to, I just haven't written up the documentation for it yet. I can reopen this PR after I finish that if you'd like to take a look

**Pull request closed without merging**
